% http://blogs.mathworks.com/loren/2007/12/11/making-pretty-graphs/
% load data
% create basic plot

function format_plot(x, y, x_label, y_label, ptitle)
	figure('Units', 'pixels', ...
		'Position', [100 100 500 375]);
	hold on;

	h_d1 = line(x, y);

	% adjust line properties (functional)
	set(h_d1                       , ...
		'LineStyle'     , '-'           , ...
		'Color'         , [0 0 0]       );

	% adjust line properties (esthetics)
	set(h_d1                       , ...
		'LineWidth'     , 2         );

	% add legend and labels
	hTitle  = title(ptitle);
	hXLabel = xlabel(x_label);
	hYLabel = ylabel(y_label);

	% adjust font and axes properties
	set( gca                      , ...
		'FontName'  , 'Helvetica' );
	set([hXLabel, hYLabel], ...
		'FontName'  , 'AvantGarde');
	set(hTitle, ...
	    'FontName'  , 'AvantGarde');
	set( hTitle                   , ...
	    'FontSize'  , 12          , ...
	    'FontWeight', 'bold'      );

	set(gca, ...
		'Box'           , 'off'     , ...
		'TickDir'       , 'out'     , ...
		'TickLength'    , [.02 .02] , ...
		'XMinorTick'    , 'on'      , ...
		'YMinorTick'    , 'on'      , ...
		'YGrid'         , 'on'      , ...
		'XColor'        , [.3 .3 .3], ...
		'YColor'        , [.3 .3 .3], ...
		'LineWidth'     , 1         );
	%     'YTick'         , 500:200:1200  , ...
	% Export to EPS

	a = gca;
	% set box property to off and remove background color
	set(a,'box','off','color','none')
	% create new, empty axes with box but without ticks
	b = axes('Position',get(a,'Position'),'box','on','xtick',[],'ytick',[]);
	% set original axes as active
	axes(a)
	% link axes in case of zooming
	linkaxes([a b])

	% set(gcf, 'PaperPositionMode', 'auto');
	% print -dpng finalPlot1.png
end